# Setup
title:               Welcome
tagline:             'Kun'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a>.'
url:                 https://learn-live.github.io/about
baseurl:            ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kun
  url:               https://twitter.com/
  email:             kun.bj@outlook.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

#theme: jekyll-theme-cayman
